Change webpack-command => webpack-cli, since the older one is deprecated and was giving me an error
Got:

    TypeError: Path must be a string. Received undefined

Upgrading to webpack-cli fixed it. webpack-command is deprecated as per:

    https://github.com/webpack-contrib/webpack-command