chore: fix version updates
There are a couple of issues with some version updates

- Only do minor version updates for `@types/fs-extra`
  This is the last major version that is compatible with typescript@3.9

- `@types/yargs` is on longer compatible with typescript@3.9 so we need
  to pin it
  - Other deps have a transient dependency on `@types/yargs` so add a
    resolution to keep the version
- `eslint-plugin-import@27` breaks something. For some reason when this
  is upgraded the build for `@scope/jsii-calc-base-of-base` fails with
  this error and I have no idea why
```
packages/jsii-rosetta/lib/languages/record-references.js:11
class RecordReferencesVisitor extends default_1.DefaultVisitor {
                                                ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (packages/jsii-rosetta/lib/languages/record-references.js:11:49)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (packages/jsii-rosetta/lib/tablets/key.js:5:29)
```

Also updated the `yarn-upgrade` workflow to have these exceptions