fix(jsii-pacmak): escape documentation in all positions (#4096)
The [AWS::Personalize::Solution.PerformAutoML](
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-personalize-solution.html#cfn-personalize-solution-performautoml) property immediately starts with an admonition, which in our system gets translated to:

```
/**
 * > Admonition!
 *
 * Normal description of the property
 */
```

We weren't expecting complex markup in the 'summary' section of the JavaDocs, so we weren't escaping it, and this was making javadoc sad:

```
/software/amazon/awscdk/services/personalize/CfnSolution.java:2211: error: bad use of '>'
  * > We don't recommend enabling automated machine learning.
```

Be sure to properly do MarkDown -> HTML conversion everywhere.



---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0