fix(python): module import fails: NameError: name 'List' is not defined (#2851)
When importing a module in Python, you can get this error:
```
NameError: name 'List' is not defined
```

JSII generated code:
```python
import abc
import builtins
import datetime
import enum
import typing

import jsii
import publication
import typing_extensions

from ._jsii import *

__all__: List[typing.Any] = []  # <--- HERE IS THE BUG

publication.publish()
```

Just need to prefix `List` with `typing.`

Related issue/pr:

- https://github.com/aws/jsii/issues/2750
- https://github.com/aws/jsii/pull/2757

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0