chore(superchain): use `pipx` instead of `pip` to install CLIs (#3913)
We recently ran into a situation where we ended up with with a Python distribution where the following failed:

```shell
$ python3
>>> import OpenSSL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.7/dist-packages/OpenSSL/crypto.py", line 3268, in <module>
    _lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
```

Because we had `cryptography==39.0.0` but `PyOpenSSL==22.0.0`, which should have been `22.1.0`.

The reason `PyOpenSSL` was held back looks to be because SAM CLI had a hardcoded dependency on the old version.

To prevent this from happening in the future, use `pipx` to install CLIs, so that each CLI gets its own virtual env and their dependency sets don't interfere with each other.



---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0