chore: fix the Python build for Python >= 3.12
Since the removal of a class in Python 3.12, we need a more modern
version of `setuptools` to work on newer Python versions.

This gets rid of the error:

```
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```